version: '3.2'
services:
  postgres:
    image: postgres:11.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./postgres-default-config/postgresql.conf:/usr/local/share/postgresql/postgresql.conf
      - ./postgres-default-config/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql

  adminer:
    image: adminer:4.6.3
    container_name: adminer
    restart: always
    ports:
      - 18080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
