server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    readyness:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, readiness

postgres:
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  db: ${POSTGRES_DB:postgres}
  user: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:example}
